### ISSUE TITLE
URLs are broken with the new marketplace

### ISSUE THREAD

**Issue by chkp-zegman** [Azure/AzureTestDrive#1]
With reference to https://github.com/Azure/AzureTestDrive/wiki/Add-Marketing-to-your-Offer

With the launch of the new marketplace in Feb 1, 2017, URLs in the form: 
https://azure.microsoft.com/marketplace/partners/[PartnerName]/[Product-Name]/
Are broken.

**Comment by Bigbrd** [comment]
Thanks for identifying this! We will have the documentation updated to be just from the brand new marketplace now :)
