### ISSUE TITLE
Connection string and example for Azure Table do not match

### ISSUE THREAD

**Issue by Quetzacoalt91** [Azure/AzureTestDrive#2]
Hello,

In https://github.com/Azure/AzureTestDrive/wiki/Instructions-for-setting-up-Azure-storage-account-for-getting-leads-in-an-Azure-table, the example given for the connection string do not match the structure to follow.

At the end, should we add a semi-colon after the key ?

Thanks

**Comment by Bigbrd** [comment]
Thanks for finding that! No semi-colon is needed at that last character there. I'll update the documentation.
