### ISSUE TITLE
TypeError: SubscriptionClient is not a constructor

### ISSUE THREAD

**Issue by juvchan** [Azure/AzureTestDrive#6]
When start a new test drive deployment session, the test drive script throws an error when trying to sign in with the service principal credential.

The same issue is reproducible in different machines with the same configuration.
Node.js version: 8.3.0

See the screenshot attached.
<img width="999" alt="azuretestdrivestartsessionerror" src="https://user-images.githubusercontent.com/618616/29159325-a15557ce-7de0-11e7-8d9d-35020de40507.PNG">

**Comment by waleedarshad-vf** [comment]
+1

**Comment by serpop** [comment]
Fixed. Thanks, @juvchan

**Comment by juvchan** [comment]
Hi @serpop , I thought my pull request will be merged into the master branch instead.
